name: lint_test_deploy
on: [workflow_dispatch, push]
jobs:
  Lint-Test-and-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      uses: actions/checkout@V3
      - name: Lint
      run:  npm lint
      - name: Test
      run: npm test
      - name: Deploy
      run: echo "Deployment..."

