name: Lint, test and deploy
on: [workflow_dispatch, push]
jobs:
  lint-test-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@V3
      - name: Lint
        run:  npm lint
      - name: Test
        run: npm test
      - name: Deploy
        run: echo "Deployment..."

